=== taftio/jmerp/data/game/JavaBean.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Bean (Property)*>
<!ATTLIST Bean
	class CDATA #REQUIRED
>
<!ELEMENT Property (Object | Collection | Map | Bean | Findable)?>
<!ATTLIST Property
	name CDATA #REQUIRED
>
<!ELEMENT Object (#PCDATA)>
<!ATTLIST Object
	class CDATA #REQUIRED
>
<!ELEMENT Collection (Bean | Object | Collection | Map)*>
<!ATTLIST Collection
	class CDATA #REQUIRED
>

<!ELEMENT Map (Bean)*>
<!ATTLIST Map
    class CDATA #REQUIRED
>

<!ELEMENT Findable (#PCDATA)>
<!ATTLIST Findable
	class CDATA #REQUIRED
	finderClass CDATA #REQUIRED
	finderKey CDATA #REQUIRED
>

=== taftio/jmerp/data/game/specialabilities/SpecialAbilityPanelFactory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.gui.swing.specialabilities.SpecialAbilityPanelFactory">
  <Property name="Panels">
    <Map class="java.util.HashMap">
        <Bean class="com.chaosserver.data.MapEntry">
          <Property name="Key">
            <Object class="java.lang.String">com.chaosserver.merp.rules.specialabilities.SkillBonusAbility</Object>
          </Property>
          <Property name="Value">
            <Object class="java.lang.String">com.chaosserver.merp.gui.swing.specialabilities.SkillBonusAbilityPanel</Object>
          </Property>
        </Bean>
    </Map>
  </Property>
</Bean>

=== taftio/jmerp/data/game/skill/MagicalCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.skill.SkillCategory">
  <Property name="Name">
    <Object class="java.lang.String">Magical</Object>
  </Property>
  <Property name="SkillList">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Read Rune</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intelligence</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">20</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Use Item</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intelligence</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">21</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Directed Spells</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">22</Object>
        </Property>
      </Bean>
    </Collection>
  </Property>
</Bean>

=== taftio/jmerp/data/game/skill/MiscellaneousCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.skill.SkillCategory">
  <Property name="Name">
    <Object class="java.lang.String">Miscellaneous</Object>
  </Property>
  <Property name="SkillList">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Perception</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intuition</Findable>
        </Property>
        <Property name="TransferToNonZero">
          <Object class="java.lang.Integer">1</Object>
        </Property>
        <Property name="TransferToZero">
          <Object class="java.lang.Integer">1</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">23</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Body Development</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Constitution</Findable>
        </Property>
        <Property name="SpecialBonus">
          <Object class="java.lang.Integer">5</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">24</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Base Spell OB</Object>
        </Property>
        <Property name="MaxRanks">
          <Object class="java.lang.Integer">0</Object>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">25</Object>
        </Property>
      </Bean>

    </Collection>
  </Property>
</Bean>
