=== taftio/jmerp/data/game/JavaBean.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Bean (Property)*>
<!ATTLIST Bean
	class CDATA #REQUIRED
>
<!ELEMENT Property (Object | Collection | Map | Bean | Findable)?>
<!ATTLIST Property
	name CDATA #REQUIRED
>
<!ELEMENT Object (#PCDATA)>
<!ATTLIST Object
	class CDATA #REQUIRED
>
<!ELEMENT Collection (Bean | Object | Collection | Map)*>
<!ATTLIST Collection
	class CDATA #REQUIRED
>

<!ELEMENT Map (Bean)*>
<!ATTLIST Map
    class CDATA #REQUIRED
>

<!ELEMENT Findable (#PCDATA)>
<!ATTLIST Findable
	class CDATA #REQUIRED
	finderClass CDATA #REQUIRED
	finderKey CDATA #REQUIRED
>

=== taftio/jmerp/data/game/skill/GeneralCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Jordan Reed (Chaos, INC.) -->
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.skill.SkillCategory">
  <Property name="Name">
    <Object class="java.lang.String">General</Object>
  </Property>
  <Property name="SkillList">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Climb</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">12</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Ride</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intuition</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">13</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Swim</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">14</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Track</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intuition</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">15</Object>
        </Property>
      </Bean>

    </Collection>
  </Property> 
</Bean>

=== taftio/jmerp/data/game/magic/SpellCategories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.magic.SpellCategories"> 
  <Property name="SpellCategories"> 
    <Collection class="java.util.ArrayList"> 
      <Bean class="com.chaosserver.merp.rules.magic.SpellCategory"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Open Essence</Object>
        </Property>
        <Property name="CategoryType">
          <Object class="java.lang.String">Realm</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.magic.SpellCategory"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Mage</Object>
        </Property>
        <Property name="CategoryType">
          <Object class="java.lang.String">Profession</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.magic.SpellCategory"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Bard</Object>
        </Property>
        <Property name="CategoryType">
          <Object class="java.lang.String">Profession</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.magic.SpellCategory"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Open Channeling</Object>
        </Property>
        <Property name="CategoryType">
          <Object class="java.lang.String">Realm</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.magic.SpellCategory"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Animist</Object>
        </Property>
        <Property name="CategoryType">
          <Object class="java.lang.String">Profession</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.magic.SpellCategory"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Ranger</Object>
        </Property>
        <Property name="CategoryType">
          <Object class="java.lang.String">Profession</Object>
        </Property>
      </Bean>
    </Collection>
  </Property>
</Bean>

=== taftio/jmerp/data/game/skill/SubterfugeCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.skill.SkillCategory">
  <Property name="Name">
    <Object class="java.lang.String">Subterfuge</Object>
  </Property>
  <Property name="SkillList">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Ambush</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">16</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Stalk/Hide</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Presence</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">17</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Pick Lock</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intelligence</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">18</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Disarm Trap</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Intuition</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">19</Object>
        </Property>
      </Bean>

    </Collection>
  </Property>
</Bean>

=== taftio/jmerp/data/game/skill/WeaponCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.skill.SkillCategory">
  <Property name="Name">
    <Object class="java.lang.String">Weapon</Object>
  </Property>
  <Property name="SkillList">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">1-H Edged</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Strength</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">6</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">1-H Concussion</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Strength</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">7</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">2-Handed</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Strength</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">8</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Thrown</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">9</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Missile</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">10</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Pole-arms</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Strength</Findable>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">2</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">11</Object>
        </Property>
      </Bean>
    </Collection>
  </Property><!-- Ends SkillList Property -->
</Bean>

=== taftio/jmerp/data/game/magic/realm/RealmList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.magic.realm.RealmList"> 
  <Property name="Realms"> 
    <Collection class="java.util.ArrayList"> 
      <Bean class="com.chaosserver.merp.rules.magic.realm.Realm"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Essence</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.magic.realm.Realm"> 
        <Property name="Name"> 
          <Object class="java.lang.String">Channeling</Object>
        </Property>
      </Bean>
    </Collection>
  </Property>
</Bean>

=== taftio/jmerp/data/game/specialabilities/SpecialAbilities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.specialabilities.SpecialAbilities">
  <Property name="SpecialAbilities">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.specialabilities.SkillBonusAbility">
        <Property name="Amount">
          <Object class="java.lang.Integer">5</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.specialabilities.SkillBonusAbility">
        <Property name="Amount">
          <Object class="java.lang.Integer">10</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.specialabilities.AnimalEmpathyAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.SensoryEnhancementAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.ResistanceAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.SpellProficientAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.MovingManeuversAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.ObservantAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.LightningReactionAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.CharismaticAbility"/>
      <Bean class="com.chaosserver.merp.rules.specialabilities.PainResistanceAbility"/>
    </Collection>
  </Property>
</Bean>

=== taftio/jmerp/data/game/skill/MovementManeuverCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.skill.SkillCategory">
  <Property name="Name">
    <Object class="java.lang.String">Movement and Maneuver</Object>
  </Property>
  <Property name="SkillList">
    <Collection class="java.util.ArrayList">
      <!-- First Bean - No Armor -->
      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">No Armor</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="MaxRanks">
          <Object class="java.lang.Integer">2</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">1</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Soft Leather</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="SpecialBonus">
          <Object class="java.lang.Integer">-15</Object>
        </Property>
        <Property name="MaxRanks">
          <Object class="java.lang.Integer">3</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">2</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Rigid Leather</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Agility</Findable>
        </Property>
        <Property name="SpecialBonus">
          <Object class="java.lang.Integer">-30</Object>
        </Property>
        <Property name="MaxRanks">
          <Object class="java.lang.Integer">5</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">3</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Chain</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Strength</Findable>
        </Property>
        <Property name="SpecialBonus">
          <Object class="java.lang.Integer">-45</Object>
        </Property>
        <Property name="MaxRanks">
          <Object class="java.lang.Integer">7</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">4</Object>
        </Property>
      </Bean>

      <Bean class="com.chaosserver.merp.rules.skill.Skill">
        <Property name="Name">
          <Object class="java.lang.String">Plate</Object>
        </Property>
        <Property name="Stat">
          <Findable class="com.chaosserver.merp.rules.stat.Stat" finderClass="com.chaosserver.merp.rules.stat.StatFinder" finderKey="Name">Strength</Findable>
        </Property>
        <Property name="SpecialBonus">
          <Object class="java.lang.Integer">-60</Object>
        </Property>
        <Property name="MaxRanks">
          <Object class="java.lang.Integer">9</Object>
        </Property>
        <Property name="ProgressionList">
          <Bean class="com.chaosserver.merp.rules.skill.ProgressionList">
            <Property name="ProgressionList">
              <Collection class="java.util.ArrayList">
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
                <Object class="java.lang.Integer">1</Object>
              </Collection>
            </Property>
          </Bean>
        </Property>
        <Property name="Id">
          <Object class="java.lang.Integer">5</Object>
        </Property>
      </Bean>
    </Collection>
  </Property>
</Bean>

=== taftio/jmerp/data/game/language/Copy of LanguageList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bean SYSTEM "../JavaBean.dtd">
<Bean class="com.chaosserver.merp.rules.language.LanguageList">
  <Property name="Languages">
    <Collection class="java.util.ArrayList">
      <Bean class="com.chaosserver.merp.rules.language.Language">
        <Property name="Name">
          <Object class="java.lang.String">Adunaic</Object>
        </Property>
      </Bean>
      <Bean class="com.chaosserver.merp.rules.language.Language">
        <Property name="Name">
          <Object class="java.lang.String">Apysaic</Object>
        </Property>
      </Bean>
    </Collection>
  </Property>
</Bean>
