=== taftio/jmerp/data/game/RollTable.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Jordan Reed (Chaos, INC.) -->
<!ELEMENT RollTableRoot (RollTable)>
<!ELEMENT RollTable (FinderObject, Row+)>
<!ELEMENT Row (PrimaryKey | RollTable)>
<!ATTLIST Row
	min CDATA #REQUIRED
	max CDATA #REQUIRED
>
<!ELEMENT FinderObject EMPTY>
<!ATTLIST FinderObject
	objectClass CDATA #REQUIRED
	finderClass CDATA #REQUIRED
	finderKey CDATA #REQUIRED
>
<!ELEMENT PrimaryKey (#PCDATA)>
<!ATTLIST RollTable
	min CDATA #REQUIRED
	max CDATA #REQUIRED
	open (TRUE | FALSE) "FALSE"
>

=== taftio/jmerp/data/game/profession/ProfessionSelectorTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Jordan Reed (Chaos, INC.) -->
<!DOCTYPE RollTableRoot SYSTEM "..\RollTable.dtd">
<RollTableRoot>
	<RollTable min="1" max="100" open="FALSE">
		<FinderObject objectClass="com.chaosserver.merp.rules.profession.Profession" finderClass="com.chaosserver.merp.rules.profession.ProfessionFinder" finderKey="Name"/>
		<Row min="1" max="30">
			<PrimaryKey>Warrior</PrimaryKey>
		</Row>
		<Row min="31" max="50">
			<PrimaryKey>Scout</PrimaryKey>
		</Row>
		<Row min="51" max="70">
			<PrimaryKey>Ranger</PrimaryKey>
		</Row>
		<Row min="71" max="75">
			<PrimaryKey>Mage</PrimaryKey>
		</Row>
		<Row min="76" max="80">
			<PrimaryKey>Animist</PrimaryKey>
		</Row>
		<Row min="81" max="100">
			<PrimaryKey>Bard</PrimaryKey>
		</Row>
	</RollTable>
</RollTableRoot>

=== taftio/jmerp/data/game/specialabilities/SpecialAbilityTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RollTableRoot SYSTEM "..\RollTable.dtd">
<RollTableRoot>
  <RollTable min="1" max="100" open="FALSE">
    <FinderObject objectClass="com.chaosserver.merp.rules.specialabilities.SpecialAbility" finderClass="com.chaosserver.merp.rules.specialabilities.SpecialAbilityFinder" finderKey="Name"/>
    <Row min="1" max="50">
      <PrimaryKey>Skill Bonus: +5</PrimaryKey>
    </Row>
    <!-- Row min="51" max="55" -->
    <Row min="51" max="60">
      <PrimaryKey>Skill Bonus: +10</PrimaryKey>
    </Row>
    <!-- Row min="56" max="60" -->
      <!-- PrimaryKey>Animal Empathy</PrimaryKey -->
    <!-- /Row -->
    <Row min="61" max="65">
      <PrimaryKey>Sensory Enhancement</PrimaryKey>
    </Row>
    <Row min="66" max="70">
      <PrimaryKey>Resistance</PrimaryKey>
    </Row>
    <Row min="71" max="75">
      <PrimaryKey>Spell Proficient</PrimaryKey>
    </Row>
    <Row min="76" max="80">
      <PrimaryKey>Adept Moving Maneuvers</PrimaryKey>
    </Row>
    <Row min="81" max="85">
      <PrimaryKey>Observant</PrimaryKey>
    </Row>
    <Row min="86" max="90">
      <PrimaryKey>Lightning Reaction</PrimaryKey>
    </Row>
    <Row min="91" max="95">
      <PrimaryKey>Charismatic</PrimaryKey>
    </Row>
    <Row min="96" max="100">
      <PrimaryKey>Pain Resistance</PrimaryKey>
    </Row>
  </RollTable>
</RollTableRoot>

=== taftio/jmerp/data/game/race/RaceSelectorTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RollTableRoot SYSTEM "..\RollTable.dtd">
<RollTableRoot>
  <RollTable min="1" max="100" open="FALSE">
    <FinderObject objectClass="com.chaosserver.merp.rules.race.Race" finderClass="com.chaosserver.merp.rules.race.RaceFinder" finderKey="Name"/>
    <Row min="1" max="3">
      <PrimaryKey>Hobbit</PrimaryKey>
    </Row>
    <Row min="4" max="8">
      <PrimaryKey>Umli</PrimaryKey>
    </Row>
    <Row min="9" max="21">
      <PrimaryKey>Dwarf</PrimaryKey>
    </Row>
    <Row min="22" max="25">
      <PrimaryKey>Wose</PrimaryKey>
    </Row>
    <Row min="26" max="75">
      <RollTable min="1" max="100" open="FALSE">
        <FinderObject objectClass="com.chaosserver.merp.rules.race.Race" finderClass="com.chaosserver.merp.rules.race.RaceFinder" finderKey="Name"/>
        <Row min="1" max="5">
          <PrimaryKey>Dúnedain</PrimaryKey>
        </Row>
        <Row min="6" max="10">
          <PrimaryKey>Rohirrim</PrimaryKey>
        </Row>
        <Row min="11" max="15">
          <PrimaryKey>Beorning</PrimaryKey>
        </Row>
        <Row min="16" max="20">
          <PrimaryKey>Woodman</PrimaryKey>
        </Row>
        <Row min="21" max="25">
          <PrimaryKey>Dorwinrim</PrimaryKey>
        </Row>
        <Row min="26" max="30">
          <PrimaryKey>Lossadan</PrimaryKey>
        </Row>
        <Row min="31" max="54">
          <PrimaryKey>Eriadoran</PrimaryKey>
        </Row>
        <Row min="55" max="78">
          <PrimaryKey>Gondorian</PrimaryKey>
        </Row>
        <Row min="79" max="83">
          <PrimaryKey>Dunlending</PrimaryKey>
        </Row>
        <Row min="84" max="86">
          <PrimaryKey>Easterling</PrimaryKey>
        </Row>
        <Row min="87" max="89">
          <PrimaryKey>Haradan</PrimaryKey>
        </Row>
        <Row min="90" max="92">
          <PrimaryKey>Corsair</PrimaryKey>
        </Row>
        <Row min="93" max="95">
          <PrimaryKey>Variag</PrimaryKey>
        </Row>
        <Row min="96" max="100">
          <PrimaryKey>Black Númenórean</PrimaryKey>
        </Row>
      </RollTable>
    </Row>
    <Row min="76" max="78">
      <PrimaryKey>Half-elf</PrimaryKey>
    </Row>
    <Row min="79" max="91">
      <PrimaryKey>Silvan Elf</PrimaryKey>
    </Row>
    <Row min="92" max="97">
      <PrimaryKey>Sinda Elf</PrimaryKey>
    </Row>
    <Row min="98" max="100">
      <PrimaryKey>Noldo Elf</PrimaryKey>
    </Row>
  </RollTable>
</RollTableRoot>
